version: 2
jobs:
  coverage:
    working_directory: ~/Newflix
    docker:
      - image: circleci/android:api-29
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - run:
          name: Send coverage
          command: bash <(curl -s https://codecov.io/bash)
  danger:
    working_directory: ~/Newflix
    docker:
      - image: circleci/android:api-29
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - run:
          name: Danger
          command: bundle exec danger --verbose
deployment:
  coverage:
    branch: [master]
    commands:
      - bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build_and_test:
    jobs:
      - coverage
